#!/usr/bin/env bash
# This script reads /etc/passwd and displays username, user id, and home directory
while IFS=: read -r user pass uid gid gecos home shell
do
  echo "$user:$uid:$home"
done < /etc/passwd
