#!/usr/bin/env bash
# This script creates a PID file and handles SIGTERM, SIGINT, and SIGQUIT differently
echo $$ > /var/run/myscript.pid
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true
do
  echo "To infinity and beyond"
  sleep 2
done
